import { config } from "dotenv"
import { resolve } from "path"
config({ path: resolve(process.cwd(), ".env.local") })
import { createClient } from "@supabase/supabase-js"

const supabase = createClient(
  process.env.NEXT_PUBLIC_SUPABASE_URL!,
  process.env.SUPABASE_SERVICE_ROLE_KEY!
)

const questions = [
  // Grammar (10)
  { skill: "grammar", difficulty: "B1", type: "mcq", prompt: "She _____ to the store before the rain started.", options: ["goes","went","has gone","had gone"], answer: 3, explanation: "Past perfect (had gone) shows action completed before another past event.", tags: ["past-perfect","tense"] },
  { skill: "grammar", difficulty: "B1", type: "mcq", prompt: "If I _____ more time, I would study harder.", options: ["have","had","would have","having"], answer: 1, explanation: 'Second conditional: "If + past simple, would + infinitive" for unreal present situations.', tags: ["conditionals","second-conditional"] },
  { skill: "grammar", difficulty: "B2", type: "mcq", prompt: "The report _____ by the team last Friday.", options: ["was submitted","submitted","has submitted","submits"], answer: 0, explanation: 'Passive voice past simple: "was/were + past participle."', tags: ["passive-voice","past-simple"] },
  { skill: "grammar", difficulty: "B2", type: "mcq", prompt: "Not only _____ late, but he also forgot his homework.", options: ["he arrived","arrived he","did he arrive","he did arrive"], answer: 2, explanation: 'Negative inversion with "not only": auxiliary verb precedes subject.', tags: ["inversion","emphasis"] },
  { skill: "grammar", difficulty: "B1", type: "mcq", prompt: "I wish I _____ speak French fluently.", options: ["can","could","will","would"], answer: 1, explanation: '"Wish + past simple" expresses desire for present/future change.', tags: ["wish-clauses","modals"] },
  { skill: "grammar", difficulty: "C1", type: "mcq", prompt: "Having _____ the assignment, she felt relieved.", options: ["finished","finish","been finished","finishing"], answer: 0, explanation: 'Participial clause: "Having + past participle" for action completed before main clause.', tags: ["participles","perfect-participle"] },
  { skill: "grammar", difficulty: "B2", type: "mcq", prompt: "The scientist whose _____ was published is presenting today.", options: ["research","researches","researching","researched"], answer: 0, explanation: 'Relative clause with "whose" + noun. "Research" is uncountable.', tags: ["relative-clauses","whose"] },
  { skill: "grammar", difficulty: "B1", type: "mcq", prompt: "Neither the students nor the teacher _____ ready.", options: ["were","was","are","is"], answer: 1, explanation: '"Neither...nor" verb agrees with the closer subject ("teacher" = singular = "was").', tags: ["subject-verb-agreement","correlative-conjunctions"] },
  { skill: "grammar", difficulty: "C1", type: "mcq", prompt: "It is essential that every student _____ the exam.", options: ["passes","pass","passed","passing"], answer: 1, explanation: "Subjunctive mood after \"essential that\": base form (no -s).", tags: ["subjunctive","that-clauses"] },
  { skill: "grammar", difficulty: "B2", type: "mcq", prompt: "He spoke so quietly that we could _____ hear him.", options: ["hardly","hard","scarcely ever","barely ever"], answer: 0, explanation: '"Hardly" = almost not. Fits "could hardly hear" — near impossibility.', tags: ["adverbs","degree"] },

  // Vocabulary (10)
  { skill: "vocab", difficulty: "B2", type: "mcq", prompt: "The new policy will _____ employees to work from home three days a week.", options: ["enable","allow","permit","entitle"], answer: 3, explanation: '"Entitle" = give official right to. Others work but "entitle" is most precise for policy/rights context.', tags: ["formal-vocab","verbs"] },
  { skill: "vocab", difficulty: "B1", type: "mcq", prompt: "The lecture was so _____ that several students fell asleep.", options: ["monotonous","rhythmic","repetitive","dull"], answer: 0, explanation: '"Monotonous" = tediously unvarying. Stronger and more precise than "dull" in academic context.', tags: ["adjectives","academic-vocab"] },
  { skill: "vocab", difficulty: "B2", type: "mcq", prompt: "Her _____ to detail made her an excellent editor.", options: ["attendance","attention","attraction","attitude"], answer: 1, explanation: '"Attention to detail" — fixed collocation.', tags: ["collocations","nouns"] },
  { skill: "vocab", difficulty: "C1", type: "mcq", prompt: "The politician tried to _____ the scandal by changing the subject.", options: ["overlook","bypass","deflect","ignore"], answer: 2, explanation: '"Deflect" = redirect attention away from. "Deflect criticism/scrutiny" is a key C1 collocation.', tags: ["C1-vocab","verbs","politics"] },
  { skill: "vocab", difficulty: "B1", type: "mcq", prompt: "We need to _____ a solution to this problem as soon as possible.", options: ["find","devise","invent","create"], answer: 1, explanation: '"Devise a solution/plan" — academic collocation. "Find" is too informal for writing context.', tags: ["collocations","academic-vocab"] },
  { skill: "vocab", difficulty: "B2", type: "mcq", prompt: "The company's profits have been _____ declining over the past year.", options: ["steadily","constantly","continuously","regularly"], answer: 0, explanation: '"Steadily declining" — standard academic/business collocation.', tags: ["adverbs","collocations","business"] },
  { skill: "vocab", difficulty: "C1", type: "mcq", prompt: "The new evidence _____ the existing theory.", options: ["contradicts","opposes","refutes","denies"], answer: 2, explanation: '"Refutes" = disproves with evidence. The strongest/most precise academic term here.', tags: ["academic-vocab","verbs","argumentation"] },
  { skill: "vocab", difficulty: "B1", type: "mcq", prompt: "The documentary had a _____ impact on public awareness.", options: ["significant","big","large","major"], answer: 0, explanation: '"Significant impact" — most natural academic collocation.', tags: ["collocations","adjectives","academic-vocab"] },
  { skill: "vocab", difficulty: "B2", type: "mcq", prompt: "She made a _____ effort to improve her pronunciation.", options: ["conscious","careful","deliberate","intentional"], answer: 2, explanation: '"Deliberate effort" — natural collocation. "Deliberate" implies purposeful, sustained action.', tags: ["collocations","adjectives"] },
  { skill: "vocab", difficulty: "C1", type: "mcq", prompt: "The report _____ several flaws in the current system.", options: ["exposed","revealed","uncovered","highlighted"], answer: 3, explanation: '"Highlighted flaws" — most common academic/report collocation.', tags: ["collocations","academic-writing","verbs"] },

  // Reading (5)
  { skill: "reading", difficulty: "B2", type: "reading", prompt: "According to the passage, what is the primary reason cities are investing in green spaces?", passage: "Urban planners across the globe are increasingly recognising the multifaceted benefits of integrating green spaces into city designs. Beyond their aesthetic appeal, parks and urban forests serve as natural air purifiers, absorbing pollutants and releasing oxygen. Furthermore, research consistently demonstrates that access to nature significantly reduces stress levels and improves mental well-being among city dwellers. Economically, properties adjacent to parks command higher prices, contributing to increased tax revenues. However, the most compelling argument driving municipal investment is the role green spaces play in mitigating the urban heat island effect, thereby reducing energy consumption during peak summer months.", options: ["Aesthetic improvement of the cityscape","Reducing energy costs by lowering urban temperatures","Increasing property values near parks","Improving air quality for residents"], answer: 1, explanation: 'The passage states the "most compelling argument" is mitigating the urban heat island effect and reducing energy consumption.', tags: ["reading-comprehension","main-idea","urban-planning"] },
  { skill: "reading", difficulty: "B2", type: "reading", prompt: 'What does the word "mitigating" (paragraph 1) most closely mean?', passage: "Urban planners across the globe are increasingly recognising the multifaceted benefits of integrating green spaces into city designs. Beyond their aesthetic appeal, parks and urban forests serve as natural air purifiers, absorbing pollutants and releasing oxygen. Furthermore, research consistently demonstrates that access to nature significantly reduces stress levels and improves mental well-being among city dwellers. Economically, properties adjacent to parks command higher prices, contributing to increased tax revenues. However, the most compelling argument driving municipal investment is the role green spaces play in mitigating the urban heat island effect, thereby reducing energy consumption during peak summer months.", options: ["Eliminating","Reducing the severity of","Studying","Causing"], answer: 1, explanation: '"Mitigating" = making less severe/harmful.', tags: ["vocabulary-in-context","reading"] },
  { skill: "reading", difficulty: "C1", type: "reading", prompt: "Which statement best describes the author's tone in this passage?", passage: "The rhetoric surrounding artificial intelligence often oscillates between utopian enthusiasm and dystopian dread, rarely pausing for measured analysis. Proponents herald AI as the solution to humanity's most intractable problems, from climate change to disease. Detractors, meanwhile, envision scenarios of mass unemployment and existential threat. Lost in this polarised discourse is a more nuanced reality: AI is a tool, powerful yet fundamentally shaped by the intentions and competencies of those who deploy it. Its consequences, therefore, are neither predetermined nor inevitable — they are a reflection of societal choices.", options: ["Enthusiastically supportive of AI development","Deeply concerned about AI risks","Balanced and analytical","Dismissive of both optimists and pessimists"], answer: 2, explanation: 'Author critiques both extremes and calls for "measured analysis" and "nuanced reality" — balanced/analytical tone.', tags: ["tone","author-purpose","inference"] },
  { skill: "reading", difficulty: "B1", type: "reading", prompt: "What can be inferred about students who take regular breaks while studying?", passage: "A growing body of research challenges the popular notion that longer, uninterrupted study sessions lead to better academic outcomes. Studies indicate that the brain's ability to retain new information diminishes significantly after sustained focus of more than 45 minutes. In contrast, students who incorporate short breaks — typically 10 to 15 minutes — every hour demonstrate markedly improved recall during assessments. These findings suggest that strategic rest is not a sign of laziness but rather an essential component of effective learning.", options: ["They are less disciplined than those who study without breaks","They tend to perform better on tests","They study for longer total hours","They find studying easier"], answer: 1, explanation: 'Passage states students with breaks show "markedly improved recall during assessments" = perform better on tests.', tags: ["inference","reading-comprehension","study-skills"] },
  { skill: "reading", difficulty: "B2", type: "reading", prompt: "Which title best captures the main idea of the passage?", passage: "A growing body of research challenges the popular notion that longer, uninterrupted study sessions lead to better academic outcomes. Studies indicate that the brain's ability to retain new information diminishes significantly after sustained focus of more than 45 minutes. In contrast, students who incorporate short breaks — typically 10 to 15 minutes — every hour demonstrate markedly improved recall during assessments. These findings suggest that strategic rest is not a sign of laziness but rather an essential component of effective learning.", options: ["Why Students Struggle to Focus","The Science of Smarter Studying: Why Breaks Matter","How to Study for Six Hours a Day","Memory Loss and Academic Performance"], answer: 1, explanation: "Main idea: strategic breaks improve learning outcomes.", tags: ["main-idea","title-selection","reading"] },

  // Listening (5)
  { skill: "listening", difficulty: "B1", type: "listening", prompt: "What is the main topic of the lecture excerpt?", audio_text: "Good morning, everyone. Today we're going to explore a concept that has transformed modern economics: the idea of opportunity cost. At its simplest, opportunity cost refers to the value of the next best alternative you give up when making a choice. For instance, if you spend Saturday studying, the opportunity cost might be the football match you could have attended. Understanding this concept helps us make more rational decisions, both in our personal lives and in national economic policy.", options: ["The history of modern economics","Understanding opportunity cost in economics","How to study effectively on weekends","The importance of rational decision-making"], answer: 1, explanation: 'Speaker explicitly introduces "opportunity cost" as today\'s topic.', tags: ["listening-comprehension","main-topic","economics"] },
  { skill: "listening", difficulty: "B2", type: "listening", prompt: 'According to the speaker, what does "opportunity cost" mean?', audio_text: "Good morning, everyone. Today we're going to explore a concept that has transformed modern economics: the idea of opportunity cost. At its simplest, opportunity cost refers to the value of the next best alternative you give up when making a choice. For instance, if you spend Saturday studying, the opportunity cost might be the football match you could have attended. Understanding this concept helps us make more rational decisions, both in our personal lives and in national economic policy.", options: ["The total cost of all available alternatives","The financial cost of making a wrong decision","The value of the best alternative you forgo","The time spent considering different options"], answer: 2, explanation: 'Speaker defines it as "the value of the next best alternative you give up when making a choice."', tags: ["listening-detail","definition","economics"] },
  { skill: "listening", difficulty: "B1", type: "listening", prompt: "What example does the speaker use to illustrate opportunity cost?", audio_text: "Good morning, everyone. Today we're going to explore a concept that has transformed modern economics: the idea of opportunity cost. At its simplest, opportunity cost refers to the value of the next best alternative you give up when making a choice. For instance, if you spend Saturday studying, the opportunity cost might be the football match you could have attended. Understanding this concept helps us make more rational decisions, both in our personal lives and in national economic policy.", options: ["Choosing between two job offers","Spending Saturday studying instead of watching a football match","Making decisions about national economic policy","Calculating the cost of university tuition"], answer: 1, explanation: 'Speaker gives this exact example: "if you spend Saturday studying, the opportunity cost might be the football match."', tags: ["listening-detail","examples","economics"] },
  { skill: "listening", difficulty: "B2", type: "listening", prompt: "Listen and identify the speaker's conclusion.", audio_text: "To summarise our discussion on climate adaptation: cities cannot afford to wait for perfect solutions. The evidence overwhelmingly suggests that early investment in flood defences, heat-resistant infrastructure, and urban greening yields far greater long-term savings than reactive measures taken after a disaster. Municipalities that have already embraced proactive planning report not only reduced damage costs but also improved public health outcomes and increased investor confidence. The message is clear: act now, or pay significantly more later.", options: ["Cities should wait for better technology before investing in adaptation","Proactive climate investment saves money and improves outcomes","Flood defences are the most important adaptation measure","Investors are currently avoiding climate-vulnerable cities"], answer: 1, explanation: 'Speaker\'s conclusion: "act now, or pay significantly more later" — proactive investment yields better outcomes.', tags: ["listening-conclusion","inference","climate"] },
  { skill: "listening", difficulty: "C1", type: "listening", prompt: "What is the speaker's attitude toward reactive disaster measures?", audio_text: "To summarise our discussion on climate adaptation: cities cannot afford to wait for perfect solutions. The evidence overwhelmingly suggests that early investment in flood defences, heat-resistant infrastructure, and urban greening yields far greater long-term savings than reactive measures taken after a disaster. Municipalities that have already embraced proactive planning report not only reduced damage costs but also improved public health outcomes and increased investor confidence. The message is clear: act now, or pay significantly more later.", options: ["Supportive — they are necessary in emergencies","Neutral — both approaches have equal merit","Critical — they are more costly than proactive measures","Uncertain — more research is needed"], answer: 2, explanation: "Speaker contrasts reactive measures unfavourably with proactive ones, implying reactive = costlier and less effective.", tags: ["speaker-attitude","inference","critical-listening"] },
]

async function main() {
  console.log(`Seeding ${questions.length} questions...`)
  const { error } = await supabase.from("questions").insert(questions)
  if (error) {
    console.error("Error:", error.message)
    process.exit(1)
  }
  console.log("Done.")
}

main()
